name: Deploy to GitHub Pages
on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on (ref).'
        required: false
        default: 'dev'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      - name: Setup Node
        uses: actions/setup-node@v6.3.0

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          VITE_GOOGLE_MAPS_API_KEY: ${{ vars.GOOGLE_MAPS_API_KEY }}
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v7.0.0
        with:
          name: production-files
          path: ./dist

      - name: Upload osmbuildings
        uses: actions/upload-artifact@v7.0.0
        with:
          name: osmbuildings
          path: ./osmbuildings


  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: production-files
          path: ./dist

#      - name: Display structure of downloaded files
#        run: ls -R
#        working-directory: ./dist

      - name: Download osmbuildings
        uses: actions/download-artifact@v8.0.1
        with:
          name: osmbuildings
          path: ./osmbuildings

#      - name: Display structure of downloaded files
#        run: ls -R
#        working-directory: ./osmbuildings

#      Move osmbuildings to dist
      - name: Move osmbuildings to dist
        run: mv ./osmbuildings ./dist

#      - name: Display structure of downloaded files
#        run: ls -R
#        working-directory: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: dualmaps.eu
