name: Deploy to GitHub Pages
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Upload osmbuildings
        uses: actions/upload-artifact@v4
        with:
          name: osmbuildings
          path: ./osmbuildings


  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

#      - name: Display structure of downloaded files
#        run: ls -R
#        working-directory: ./dist

      - name: Download osmbuildings
        uses: actions/download-artifact@v4
        with:
          name: osmbuildings
          path: ./osmbuildings

#      - name: Display structure of downloaded files
#        run: ls -R
#        working-directory: ./osmbuildings

#      Move osmbuildings to dist
      - name: Move osmbuildings to dist
        run: mv ./osmbuildings ./dist

#      - name: Display structure of downloaded files
#        run: ls -R
#        working-directory: ./dist

      - name: Set up environment variables
        run: echo "VITE_GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: dualmaps.eu
